polls/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('register', views.RegisterView.as_view(), name='register'),
    # path('profile/<int:pk>',)
    path('about', views.AboutView.as_view(), name='about'),
    path('suggest', login_required(views.SuggestView.as_view()), name='suggest'),
    path('places', views.PlacesView.as_view(), name='places'),
]

smakan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('__reload__/', include('django_browser_reload.urls'))
]

polls/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.core.validators import RegexValidator

class UserManager(BaseUserManager):
    def _create_user(self, email, username, pin, **kwargs):
        if not email:
            raise ValueError('Please provide a valid e-mail.')

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **kwargs)
        user.set_pin(pin)
        user.save()
        return user
    
    def create_user(self, email=None, username=None, pin=None, **kwargs):
        kwargs.setdefault('is_staff', False)
        kwargs.setdefault('is_superuser', False)
        if pin is None:
            raise ValueError('A 4-digit PIN must be supplied.')
        
        return self._create_user(email=email, username=username, pin=pin, **kwargs)

    def create_superuser(self, email=None, username=None, pin=None, **kwargs):
        kwargs.setdefault('is_staff', True)
        kwargs.setdefault('is_superuser', True)

        if pin is None:
            raise ValueError('A 4-digit PIN must be supplied.')

        return self._create_user(email=email, username=username, pin=pin, **kwargs)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(blank=False, default='', unique=True)
    username = models.CharField(max_length=255, blank=False, default='')
    pin_regex = RegexValidator(regex=r"^[0-9]{4,4}$", message="Please enter a 4-digit pin")
    pin = models.IntegerField(blank=False, validators=[pin_regex])

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def get_name(self):
        return self.username

    def set_pin(self, pin):
        self.pin = pin
        self.save()

    def check_pin(self, pin):
        return self.pin == pin

polls/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm, SetPasswordForm, AuthenticationForm
from .models import User

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'username', 'pin')
        widgets = {
            
            'pin': forms.PasswordInput()
        }

class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user_cache = None
        self.fields['email'].label = 'Email'
        self.fields['pin'].label = 'PIN'
        self.fields.pop('username', None)
        self.fields.pop('password', None)
    
    email = forms.EmailField(widget=forms.EmailInput(attrs={'autofocus': True}))
    pin = forms.IntegerField(widget=forms.PasswordInput())
    # TODO add validation

    
    def clean(self):
        email = self.cleaned_data.get('email')
        pin = self.cleaned_data.get('pin')
        if email and pin:
            self.user_cache = authenticate(self.request, email=email, pin=pin)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)
        return self.cleaned_data

class CreatePlaceForm(forms.Form):
    pass

class UpdatePlaceForm(forms.Form):
    pass

class CreateSuggestionForm(forms.Form):
    pass

class UpdateSuggestionForm(forms.Form):
    pass

polls/views.py
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView, View, DetailView
from django.views.generic.edit import CreateView

from .models import User
from .forms import CustomLoginForm, RegisterForm

class HomeView(TemplateView):
    template_name = 'polls/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add recent events filter
        return context
    
class Login(LoginView):
    template_name = 'polls/login.html'
    redirect_authenticated_user = True
    authentication_form = CustomLoginForm

class Logout(LogoutView):
    next_page = 'polls:login'
    
class RegisterView(CreateView):
    template_name_suffix = '_create_form'
    model = User
    form_class = RegisterForm
    
    def get_success_url(self):
        return reverse('polls:index')

    def form_valid(self, form):
        response = super().form_valid(form)
        email = form.cleaned_data['email']
        pin = form.cleaned_data['pin']
        user = authenticate(email=email, pin=pin)
        if user is not None:
            login(self.request, user)
        return response

class AboutView(TemplateView):
    template_name = 'polls/about.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

# @login_required - add this on the urls by wrapping this view func in the wrapper - eg login_required(SuggestView.as_view())
class SuggestView(TemplateView):
    template_name = 'polls/suggest.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class PlacesView(TemplateView):
    template_name = 'polls/places.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ProfileView(DetailView):
    pass

polls/templates/polls/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}
<section class="mx-auto px-20 max-w-5xl py-20">
  <h1 class="text-5xl font-bold text-center mb-8">This is the About page</h1>
</section>
{% endblock content %}

polls/templates/polls/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Let's-makan together!{% endblock title %}

{% block content %}
<section class="mx-auto px-20 max-w-5xl py-20">
  <h1 class="text-5xl font-bold text-center mb-8">Let's smakan together!</h1>
  <p class="text-lg text-center mb-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
  <div class="mx-auto max-w-md mb-12">
    <form class="flex items-center border-2 border-gray-300 rounded-md px-4 py-2">
      <input type="text" placeholder="Search..." class="input input-ghost w-full"/>
      <button type="submit" class="btn btn-primary">Go</button>
    </form>
  </div>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    <div class="card shadow-lg">
      <div class="card-body">
        <h2 class="card-title">Eatery 1</h2>
        <p class="text-gray-600 mb-4">If a dog chews shoes whose shoes does he choose?</p>
        <div class="card-actions">
          <button class="btn btn-sm btn-outline">Go!</button>
        </div>
      </div>
    </div>
    <div class="card shadow-lg">
      <div class="card-body">
        <h2 class="card-title">Eatery 2</h2>
        <p class="text-gray-600 mb-4">If a dog chews shoes whose shoes does he choose?</p>
        <div class="card-actions">
          <button class="btn btn-sm btn-outline">Go!</button>
        </div>
      </div>
    </div>
    <div class="card bg-base-100 shadow-lg">
      <div class="card-body">
        <h2 class="card-title">Eatery 3</h2>
        <p class="text-gray-600 mb-4">If a dog chews shoes whose shoes does he choose?</p>
        <div class="card-actions">
          <button class="btn btn-sm btn-outline">Go!</button>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

polls/templates/polls/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
<section class="mx-auto my-10 p-20 max-w-xl">
  <h1 class="text-5xl font-bold text-center mb-4">Log in to dine in</h1>
  <p class="italic text-center text-sm text-gray-600 mb-8">or out, don't let me tell you what you can or can't do</p>
  <form method="post" class="flex flex-col">
    {% csrf_token %}
    <div class="text-gray-600 text-sm mb-0.5">
      {{ form.email.label_tag }}
    </div>
    {{ form.email }}
    <div class="text-gray-600 text-sm mb-0.5 mt-2">
      {{ form.pin.label_tag }}
    </div>
    {{ form.pin }}
    <input class="btn mt-2" type="submit" value="Login">
    <div class="text-gray-600 text-sm mb-0.5 mt-2">
      Don't have an account yet? <a class="underline" href="{% url 'polls:register' %}">Register now</a>.
    </div>
    <div class="text-gray-600 text-sm mb-2 mt-0.5">
      Forgot your password? Haiyaaa password reset link not done yet le.
    </div>
</form>
</section>
{% endblock content %}

polls/templates/polls/places.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Places{% endblock title %}

{% block content %}
<section class="mx-auto px-20 max-w-5xl py-20">
  <h1 class="text-5xl font-bold text-center mb-8">This is the Places page</h1>
</section>
{% endblock content %}

polls/templates/polls/suggest.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Suggest{% endblock title %}

{% block content %}
<section class="mx-auto px-20 max-w-5xl py-20">
  <h1 class="text-5xl font-bold text-center mb-8">Suggest a new place to eat here!</h1>
</section>
{% endblock content %}

polls/templates/polls/user_create_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register{% endblock title %}

{% block content %}
<section class="mx-auto my-10 p-20 max-w-xl">
  <h1 class="text-5xl font-bold text-center mb-8">Register now, makan later</h1>
  <form method="post" class="flex flex-col">
    {% csrf_token %}
    <div class="text-gray-600 text-sm mb-0.5">
      {{ form.username.label_tag }}
    </div>
    {{ form.username }}
    <div class="text-gray-600 text-sm mb-0.5 mt-2">
      {{ form.email.label_tag }}
    </div>
    {{ form.email }}
    <div class="text-gray-600 text-sm mb-0.5 mt-2">
      {{ form.pin.label_tag }}
    </div>
    {{ form.pin }}
    <input class="btn mt-2" type="submit" value="Register">
    <div class="text-gray-600 text-sm mb-0.5 mt-2">
      Got an account already? <a class="underline" href="{% url 'polls:login' %}">Login instead</a>.
    </div>
</form>
</section>
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" data-theme="lofi">
	<head>
	<link rel="shortcut icon" href="{% static 'favicon/favicon.png' %}"/>
    <title>{% block title %}{% endblock title %} | SMAKAN</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body>
		<div class="drawer">
			<input id="my-drawer-4" type="checkbox" class="drawer-toggle"/>
			<div class="drawer-content flex flex-col">
				<!-- Navbar -->
				<div class="w-full navbar primary-content justify-around py-10 lg:py-5 px-20">
					<div class="flex-1 px-2 mx-2 text-xl font-bold"><a href="{% url 'polls:index' %}">🍲 smakan</a></div>
					<div>
						<div class="hidden lg:block">
							<ul class="menu menu-horizontal">
								<!-- Navbar menu content here -->
								<li><a href="{% url 'polls:suggest' %}">Suggest</a></li>
								<li><a href="{% url 'polls:places' %}">Places</a></li>
								<li><a href="{% url 'polls:about' %}">About</a></li>
								{% if user.is_authenticated %}
								<li><a>Profile</a></li>
								{% endif %}
							</ul>
						</div>
						{% if user.is_authenticated %}
						<button class="btn btn-outline mx-2"><a href="{% url 'polls:logout' %}">Logout</a></button>
						{% else %}
						<button class="btn mx-2"><a href="{% url 'polls:login' %}">Login</a></button>
						{% endif %}
						<div class="flex-none lg:hidden">
							<label for="my-drawer-4" class="btn btn-square btn-ghost">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
									class="inline-block w-6 h-6 stroke-current">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
										d="M4 6h16M4 12h16M4 18h16"></path>
								</svg>
							</label>
						</div>
					</div>
				</div>
				<!-- Content here -->
				{% block content %}{% endblock content %}
			</div>
			<div class="drawer-side">
				<label for="my-drawer-4" class="drawer-overlay"></label>
				<ul class="menu p-8 w-80 bg-base-100">
					<!-- Sidebar content here -->
					<li><a href="{% url 'polls:suggest' %}">Suggest</a></li>
					<li><a href="{% url 'polls:places' %}">Places</a></li>
					<li><a href="{% url 'polls:about' %}">About</a></li>
					{% if user.is_authenticated %}
					<li><a>Profile</a></li>
					<li class="mt-auto"><a href="{% url 'polls:logout' %}">Logout</a></li>
					<li class="italic"><a>Made with 🖤  - Dylan</a></li>
					{% else %}
					<li class="mt-auto italic"><a>Made with 🖤  - Dylan</a></li>
					{% endif %}
				</ul>				
			</div>
		</div>
		
	</body>
</html>